// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "./Game.bs.js";
import * as Config from "./Config.bs.js";

var initialState_board = Game.makeRandomGrid(Config.nbrows, Config.nbcols);

var initialState = {
  board: initialState_board,
  isWin: false
};

function board(self, action, _state) {
  if (action) {
    return Game.toggleTile(self, action._0);
  } else {
    return Game.makeRandomGrid(Config.nbrows, Config.nbcols);
  }
}

function root(state, action) {
  return {
          board: board(state.board, action, state),
          isWin: false
        };
}

var Reducers = {
  board: board,
  root: root
};

export {
  initialState ,
  Reducers ,
}
/* initialState Not a pure module */
