// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Case(Props) {
  var cell = Props.cell;
  var onToggle = Props.onToggle;
  var url = cell.seen ? (
      cell.isMine ? (require('../sprites/bomb.png')) : (
          cell.nbm === 0 ? (require('../sprites/empty.png')) : (require(`../sprites/${cell.nbm}.png`))
        )
    ) : (require('../sprites/empty.png'));
  var handleMouseEvent = React.useCallback((function (callback) {
          return function (e) {
            if (e.nativeEvent.which === 1) {
              return Curry._1(callback, undefined);
            }
            
          };
        }), []);
  return React.createElement("div", {
              className: "border-1 case-item border-black rounded-sm",
              onClick: Curry._1(handleMouseEvent, onToggle)
            }, React.createElement("img", {
                  src: url
                }));
}

var make = Case;

export {
  make ,
}
/* react Not a pure module */
