// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Grid from "./Grid.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Model from "../lib/Model.bs.js";
import * as React from "react";

function Mineswepper(Props) {
  var match = React.useReducer(Model.Reducers.root, Model.initialState);
  var dispatch = match[1];
  var handleToggleTile = React.useCallback((function (y) {
          return function (x) {
            return Curry._1(dispatch, /* Toggle */{
                        _0: [
                          y,
                          x
                        ]
                      });
          };
        }), []);
  return React.createElement("div", {
              className: "container mx-auto app mt-10"
            }, React.createElement(Grid.make, {
                  data: match[0].board,
                  onToggle: handleToggleTile
                }));
}

var R;

var make = Mineswepper;

export {
  R ,
  make ,
}
/* Grid Not a pure module */
