// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function ResetButton(Props) {
  var reset = Props.reset;
  return React.createElement("div", {
              className: "text-center cursor-pointer",
              onClick: (function (param) {
                  Curry._1(reset, undefined);
                })
            }, "Reset");
}

var R;

var make = ResetButton;

export {
  R ,
  make ,
}
/* react Not a pure module */
