// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Root(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "container mx-auto"
            }, React.createElement("div", {
                  className: "text-2xl leading-6	py-10 text-gray-600 text-center"
                }, React.createElement("span", {
                      className: "animate-bounce inline-flex"
                    }, "Mineswepper")), children);
}

var make = Root;

export {
  make ,
}
/* react Not a pure module */
