// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Root from "./components/Root.bs.js";
import * as React from "react";
import * as Mineswepper from "./components/Mineswepper.bs.js";

import './main.css'
;

var app = React.createElement(Root.make, {
      children: React.createElement(Mineswepper.make, {})
    });

export {
  app ,
}
/*  Not a pure module */
